import type { TrackerData } from "./types";

export const emptyData: TrackerData = {
  cycles: [],
  logs: [],
  cloudSync: {
    enabled: false,
    providerLabel: "",
  },
};

export const sampleData: TrackerData = {
  profile: {
    lastPeriodStart: "2026-04-24",
    typicalPeriodLength: 5,
    typicalCycleLength: 34,
    irregularCycles: true,
    birthControlUse: "None currently",
    pregnancyTracking: "not-tracking",
    trackingNeeds: ["PCOS pattern awareness", "stress and pain trends"],
    reminders: {
      periodWindow: true,
      medication: true,
      symptoms: true,
      latePeriod: true,
    },
    privacy: {
      passcodeEnabled: false,
      biometricEnabled: false,
    },
    onboardedAt: "2026-05-14",
  },
  cycles: [
    { id: "cycle-1", startDate: "2025-10-08", endDate: "2025-10-12" },
    { id: "cycle-2", startDate: "2025-11-12", endDate: "2025-11-16" },
    { id: "cycle-3", startDate: "2025-12-20", endDate: "2025-12-25" },
    { id: "cycle-4", startDate: "2026-01-22", endDate: "2026-01-27" },
    { id: "cycle-5", startDate: "2026-02-28", endDate: "2026-03-04" },
    { id: "cycle-6", startDate: "2026-03-28", endDate: "2026-04-01" },
    { id: "cycle-7", startDate: "2026-04-24", endDate: "2026-04-29" },
  ],
  logs: [
    {
      id: "log-1",
      date: "2026-04-24",
      flow: "medium",
      symptoms: ["cramps", "fatigue", "bloating"],
      mood: "irritable",
      painLevel: 6,
      medications: "Ibuprofen",
      birthControl: "",
      ovulationSigns: [],
      cervicalMucus: "none",
      sexualActivity: "none",
      notes: "Period started in the evening.",
    },
    {
      id: "log-2",
      date: "2026-04-25",
      flow: "heavy",
      symptoms: ["cramps", "headache", "cravings"],
      mood: "emotional",
      painLevel: 7,
      medications: "Ibuprofen",
      birthControl: "",
      ovulationSigns: [],
      cervicalMucus: "none",
      sexualActivity: "none",
      notes: "Used heat pack.",
    },
    {
      id: "log-3",
      date: "2026-05-07",
      symptoms: ["acne", "breast tenderness"],
      mood: "energetic",
      painLevel: 1,
      medications: "",
      birthControl: "",
      ovulationSigns: ["egg-white mucus"],
      cervicalMucus: "egg-white",
      temperature: 36.7,
      sexualActivity: "protected",
      notes: "Clear mucus and mild side pain.",
    },
    {
      id: "log-4",
      date: "2026-05-12",
      symptoms: ["fatigue", "cravings"],
      mood: "anxious",
      painLevel: 2,
      medications: "",
      birthControl: "",
      ovulationSigns: ["temperature shift"],
      cervicalMucus: "creamy",
      temperature: 36.9,
      sexualActivity: "none",
      notes: "Sleep was short.",
    },
  ],
  cloudSync: {
    enabled: false,
    providerLabel: "",
  },
};
